### ISSUE TITLE
sls-dev-tools does not work with with --profile option

### ISSUE THREAD

**Issue by TLaue** [Theodo-UK/sls-dev-tools#115]
**Describe the bug**
I am trying to run sls-dev-tools in an environment with several AWS accounts in which one of them have all the IAM users and all the others provide IAM roles to allow access. Additionally, MFA is required to access these accounts. The AWS Config file contains the required definitions like : 

[profile xxx]
source_profile = yyy
role_arn = arn:aws:iam::xxx:role/xxx
mfa_serial = arn:aws:iam::xxx:mfa/xxx
region = xxx

When I am trying to run sls-dev-tools with the --profile xxx option the following error occurs:

UnhandledPromiseRejectionWarning: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
    at SharedIniFileCredentials.load (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:101:11)
    at SharedIniFileCredentials.coalesceRefresh (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:168:10)
    at SharedIniFileCredentials.get (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/config.js:391:24)
    at Config.getCredentials (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/config.js:411:9)
    at Request.VALIDATE_CREDENTIALS (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/event_listeners.js:81:26)
    at Request.callListeners (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
    at Request.emit (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/request.js:683:14)

I am happy to provide any further details if required. Thanks for any help!

**Comment by DotGav** [comment]
@TLaue Thank you for raising this for us! During testing we have only been working with profiles stored in environment variables or the credentials file and had not tested it with the .aws/config file. This will be fixed in the next release

**Comment by TLaue** [comment]
@DotGav: This problem has not been fixed for me. I am still facing the same problem even with the latest version 1.0.3 of sls-dev-tools. The error message is still the same.
