### ISSUE TITLE
npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none was installed.

### ISSUE THREAD

**Issue by gvasquez-waypoint** [Theodo-UK/sls-dev-tools#17]
Cannot get npm to install related dependencies

```
npm install -g sls-dev-tools
/Users/gonzalovasquez/.nvm/versions/node/v6.9.0/bin/sls-dev-tools -> /Users/gonzalovasquez/.nvm/versions/node/v6.9.0/lib/node_modules/sls-dev-tools/lib/index.js
/Users/gonzalovasquez/.nvm/versions/node/v6.9.0/lib
└─┬ sls-dev-tools@0.0.3 
  ├─┬ aws-sdk@2.543.0 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.3.1 
  │ │ └── isarray@1.0.0 
  │ ├── events@1.1.1 
  │ ├── ieee754@1.1.13 
  │ ├── jmespath@0.15.0 
  │ ├── querystring@0.2.0 
  │ ├── sax@1.2.1 
  │ ├─┬ url@0.10.3 
  │ │ └── punycode@1.3.2 
  │ ├── uuid@3.3.2 
  │ └─┬ xml2js@0.4.19 
  │   └── xmlbuilder@9.0.7 
  ├── blessed@0.1.81 
  ├─┬ blessed-contrib@4.8.18 
  │ ├── ansi-term@0.0.2 
  │ ├─┬ chalk@1.1.3 
  │ │ ├── ansi-styles@2.2.1 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ ├── has-ansi@2.0.0 
  │ │ └── supports-color@2.0.0 
  │ ├─┬ drawille-canvas-blessed-contrib@0.1.3 
  │ │ ├── bresenham@0.0.3 
  │ │ ├── drawille-blessed-contrib@1.0.0 
  │ │ └── gl-matrix@2.8.1 
  │ ├── lodash@4.17.15 
  │ ├── map-canvas@0.1.5 
  │ ├── UNMET PEER DEPENDENCY marked@0.7.0
  │ ├─┬ marked-terminal@1.7.0 
  │ │ ├─┬ cardinal@1.0.0 
  │ │ │ ├── ansicolors@0.2.1 
  │ │ │ └─┬ redeyed@1.0.1 
  │ │ │   └── esprima@3.0.0 
  │ │ ├─┬ cli-table@0.3.1 
  │ │ │ └── colors@1.0.3 
  │ │ ├── lodash.assign@4.2.0 
  │ │ └─┬ node-emoji@1.10.0 
  │ │   └── lodash.toarray@4.4.0 
  │ ├─┬ memory-streams@0.1.3 
  │ │ └─┬ readable-stream@1.0.34 
  │ │   ├── core-util-is@1.0.2 
  │ │   ├── inherits@2.0.4 
  │ │   ├── isarray@0.0.1 
  │ │   └── string_decoder@0.10.31 
  │ ├── memorystream@0.3.1 
  │ ├─┬ picture-tuber@1.0.2 
  │ │ ├── buffers@0.1.1 
  │ │ ├── charm@0.1.2 
  │ │ ├─┬ event-stream@0.9.8 
  │ │ │ └── optimist@0.2.8 
  │ │ ├─┬ optimist@0.3.7 
  │ │ │ └── wordwrap@0.0.3 
  │ │ └── png-js@0.1.1 
  │ ├─┬ sparkline@0.1.2 
  │ │ ├── here@0.0.2 
  │ │ └─┬ nopt@2.1.2 
  │ │   └── abbrev@1.1.1 
  │ ├─┬ strip-ansi@3.0.1 
  │ │ └── ansi-regex@2.1.1 
  │ ├── term-canvas@0.0.5 
  │ └── x256@0.0.2 
  ├── commander@3.0.2 
  ├── moment@2.24.0 
  ├─┬ prop-types@15.7.2 
  │ ├─┬ loose-envify@1.4.0 
  │ │ └── js-tokens@4.0.0 
  │ ├── object-assign@4.1.1 
  │ └── react-is@16.10.2 
  └── react@16.10.2 

npm WARN marked-terminal@1.7.0 requires a peer of marked@^0.3.3 but none was installed.

```

```
npm -v
3.10.8

```

**Comment by DotGav** [comment]
@gvasquez-waypoint This is caused by a dependancy blessed-contrib (https://github.com/yaronn/blessed-contrib) having an out of date dependancy for marked-terminal.
The best practice for this is to ignore the npm message as it is only a warning and the library will still work as intended!

Hope this helps 😄

**Comment by gvasquez-waypoint** [comment]
> @gvasquez-waypoint I'm getting the same warning but the tool still runs fine.
> Can you run `sls-dev-tools --version` to verify the tool is working for you?
> 
> We will add resolving this to our backlog / any PRs welcome :)

It doesn't work for me:

  ```
sls-dev-tools --version
/Users/gonzalovasquez/.nvm/versions/node/v6.9.0/lib/node_modules/sls-dev-tools/lib/index.js:133
  async render() {
        ^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by gvasquez-waypoint** [comment]
> @gvasquez-waypoint This is caused by a dependancy blessed-contrib (https://github.com/yaronn/blessed-contrib) having an out of date dependancy for marked-terminal.
> The best practice for this is to ignore the npm message as it is only a warning and the library will still work as intended!
> 
> Hope this helps 😄

Unfortunately, it doesn't work in my environment as I just replied on the previous comment by @BenEllerby 

Is there anything else I could provide to identify what might be wrong?
