### ISSUE TITLE
sls-dev-tools guardin does not work with --profile option correctly

### ISSUE THREAD

**Issue by TLaue** [Theodo-UK/sls-dev-tools#243]
(compare #115) I am trying to run sls-dev-tools guardian in an environment with several AWS accounts in which one of them have all the IAM users and all the others provide IAM roles to allow access. Additionally, MFA is required to access these accounts. The AWS Config file contains the required definitions like :

[profile xxx]
source_profile = yyy
role_arn = arn:aws:iam::xxx:role/xxx
mfa_serial = arn:aws:iam::xxx:mfa/xxx
region = xxx

When I am trying to run sls-dev-tools with the --profile xxx option the following error occurs:

SharedIniFileCreds Error: Error: No active screen.
  Error [CredentialsError]: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1
      at ModalLayout.Node (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/blessed/lib/widgets/node.js:57:13)
      at ModalLayout.Element (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/blessed/lib/widgets/element.js:49:8)
      at new Layout (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/blessed/lib/widgets/layout.js:34:11)
      at new ModalLayout (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/lib/components/modalLayout.js:7:5)
      at promptMfaModal (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/lib/modals/promptMfaModal.js:14:21)
      at SharedIniFileCredentials.tokenCodeFn (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/lib/services/awsCredentials.js:14:69)
      at SharedIniFileCredentials.loadRoleProfile (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:235:12)
      at SharedIniFileCredentials.load (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:123:14)
      at SharedIniFileCredentials.coalesceRefresh (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials.js:205:12)
      at SharedIniFileCredentials.refresh (/home/thomas/.nvm/versions/node/v12.16.1/lib/node_modules/sls-dev-tools/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:168:10) {
    message: 'Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1',
    code: 'CredentialsError',
    time: 2020-05-12T14:17:05.793Z,
    originalError: {
      message: 'Could not load credentials from SharedIniFileCredentials',
      code: 'CredentialsError',
      time: 2020-05-12T14:17:05.793Z,
      originalError: { message: 'No active screen.' }
    }

I am happy to provide any further details if required. Thanks for any help!

**Comment by mansurpasha** [comment]
@TLaue Added the --mfa option to v1.1.4 to allow you to supply the token via the command line. You can use this method for Guardian, and either this or the previous method for the Dashboard. Let us know how this works!

**Comment by TLaue** [comment]
@mansurpasha It is working correctly. Thanks
